apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-tva
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: postgres-tva
    spec:
      containers:
      - name: postgres-tva
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 512Mi
