apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-tva
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: postgres-tva
    spec:
      containers:
      - name: postgres-tva
        image: quay.io/h0tbird/tva-postgres:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
