apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-tva
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: worker-tva
    spec:
      containers:
      - name: worker-tva
        image: quay.io/h0tbird/tva-worker:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
