{{- if ne .Values.environment "devel" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: voting-tva
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: vote.softonic.io
    http:
      paths:
      - backend:
          serviceName: voting-tva
          servicePort: 80
        path: /
{{- end -}}
