apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: voting-tva
  annotations:
    {{- if eq .Values.environment "devel" }}
    ingress.kubernetes.io/rewrite-target: /
    {{- else }}
    kubernetes.io/ingress.class: gce
    {{- end }}
spec:
  backend:
    servicePort: 80
  {{- if eq .Values.environment "devel" }}
    serviceName: default-http-backend
  rules:
    - host: vote.minikube.io
      http:
        paths:
        - path: /
          backend:
            serviceName: voting-tva
            servicePort: 80
  {{- else }}
    serviceName: voting-tva
  {{- end }}
