apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: voting-tva
  annotations:
    {{- if eq .Values.environment "devel" }}
    ingress.kubernetes.io/rewrite-target: /
    {{- else }}
    kubernetes.io/ingress.class: traefik
    {{- end }}
spec:
  {{- if eq .Values.environment "devel" }}
  backend:
    serviceName: default-http-backend
    servicePort: 80
  {{- end }}
  rules:
  {{- if eq .Values.environment "devel" }}
  - host: vote.minikube.io
  {{- else }}
  - host: vote.softonic.io
  {{- end }}
    http:
      paths:
      - backend:
          serviceName: voting-tva
          servicePort: 80
        path: /
